#!/usr/bin/env bash
# This script creates an RSA key pair if it doesn't already exist

key_path=~/.ssh/school

if [[ -f "$key_path" ]]; then
  echo "Key pair already exists. Skipping creation."
else
  ssh-keygen -t rsa -b 4096 -C "colemanjosephcarlis@gmail.com" -f "$key_path" -N "betty"
fi

